<a href="https://colab.research.google.com/github/Lital-Ben-Baruch/Data_Visualization/blob/main/Part%20C%20-%20Grouping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part C - Grouping

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Step 3. Assign it to a variable called df_occupation.

In [3]:
df_occupation = pd.read_csv('/content/drive/My Drive/Summaries _ML_AI_CV/data_sets/pandas/occupation.csv', sep = ',')

In [4]:
df_occupation.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [5]:
df_occupation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

### Step 4. What is the average age of everyone in the DataFrame?

In [6]:
round(df_occupation.age.mean())

34

### Step 5. What is the average age of the men and women in the DataFrame?

DataFrame.groupby()
Group DataFrame using a mapper or by a Series of columns.

A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.

In [7]:
round(df_occupation.groupby('gender').age.mean()).astype(int)

gender
F    34
M    34
Name: age, dtype: int64

### Step 6. What is the average age for each occupation in the DataFrame?

In [8]:
round(df_occupation.groupby('occupation').age.mean()).astype(int)

occupation
administrator    39
artist           31
doctor           44
educator         42
engineer         36
entertainment    29
executive        39
healthcare       42
homemaker        33
lawyer           37
librarian        40
marketing        38
none             27
other            35
programmer       33
retired          63
salesman         36
scientist        36
student          22
technician       33
writer           36
Name: age, dtype: int64


### Step 7. Show the percentage of men in each occupation in descending order.

#### Option A

First, we'll look at the percentages of men and women in each occupation.

value_count() return a Series containing counts of unique values.The resulting object will be in **descending order** so that the first element is the most frequently-occurring element. Excludes NA values by default.

by using normalize=True the object returned will contain the **relative frequencies of the unique values**. The frequency is the precentage reqired, by multipying the frequency value by 100 we will get the precentge in %.

In [9]:
percent = df_occupation.groupby(["occupation"]).gender.value_counts(normalize=True)
percent100 = percent.mul(100).round(1).astype(str)+'%'
percent

occupation     gender
administrator  M         0.544304
               F         0.455696
artist         M         0.535714
               F         0.464286
doctor         M         1.000000
educator       M         0.726316
               F         0.273684
engineer       M         0.970149
               F         0.029851
entertainment  M         0.888889
               F         0.111111
executive      M         0.906250
               F         0.093750
healthcare     F         0.687500
               M         0.312500
homemaker      F         0.857143
               M         0.142857
lawyer         M         0.833333
               F         0.166667
librarian      F         0.568627
               M         0.431373
marketing      M         0.615385
               F         0.384615
none           M         0.555556
               F         0.444444
other          M         0.657143
               F         0.342857
programmer     M         0.909091
               F         0.090909
retired        M         0.928571
               F         0.071429
salesman       M         0.750000
               F         0.250000
scientist      M         0.903226
               F         0.096774
student        M         0.693878
               F         0.306122
technician     M         0.962963
               F         0.037037
writer         M         0.577778
               F         0.422222
Name: gender, dtype: float64

creating an additional DataFrame to summarize the answer

In [10]:
new_df = pd.DataFrame({'percent':percent,'percent[%]':percent100})
new_df

                       percent percent[%]
occupation    gender
administrator M       0.544304      54.4%
              F       0.455696      45.6%
artist        M       0.535714      53.6%
              F       0.464286      46.4%
doctor        M       1.000000     100.0%
educator      M       0.726316      72.6%
              F       0.273684      27.4%
engineer      M       0.970149      97.0%
              F       0.029851       3.0%
entertainment M       0.888889      88.9%
              F       0.111111      11.1%
executive     M       0.906250      90.6%
              F       0.093750       9.4%
healthcare    F       0.687500      68.8%
              M       0.312500      31.2%
homemaker     F       0.857143      85.7%
              M       0.142857      14.3%
lawyer        M       0.833333      83.3%
              F       0.166667      16.7%
librarian     F       0.568627      56.9%
              M       0.431373      43.1%
marketing     M       0.615385      61.5%
              F       0.384615      38.5%
none          M       0.555556      55.6%
              F       0.444444      44.4%
other         M       0.657143      65.7%
              F       0.342857      34.3%
programmer    M       0.909091      90.9%
              F       0.090909       9.1%
retired       M       0.928571      92.9%
              F       0.071429       7.1%
salesman      M       0.750000      75.0%
              F       0.250000      25.0%
scientist     M       0.903226      90.3%
              F       0.096774       9.7%
student       M       0.693878      69.4%
              F       0.306122      30.6%
technician    M       0.962963      96.3%
              F       0.037037       3.7%
writer        M       0.577778      57.8%
              F       0.422222      42.2%

getting only men data and sort by percentage

In [11]:
new_df.groupby(['gender']).get_group('M').sort_values(['percent'], ascending=False)

                       percent percent[%]
occupation    gender
doctor        M       1.000000     100.0%
engineer      M       0.970149      97.0%
technician    M       0.962963      96.3%
retired       M       0.928571      92.9%
programmer    M       0.909091      90.9%
executive     M       0.906250      90.6%
scientist     M       0.903226      90.3%
entertainment M       0.888889      88.9%
lawyer        M       0.833333      83.3%
salesman      M       0.750000      75.0%
educator      M       0.726316      72.6%
student       M       0.693878      69.4%
other         M       0.657143      65.7%
marketing     M       0.615385      61.5%
writer        M       0.577778      57.8%
none          M       0.555556      55.6%
administrator M       0.544304      54.4%
artist        M       0.535714      53.6%
librarian     M       0.431373      43.1%
healthcare    M       0.312500      31.2%
homemaker     M       0.142857      14.3%

#### Option B

In [12]:
male_percent = df_occupation.pivot_table(index='occupation', columns='gender', aggfunc='size', fill_value=0)

# Calculate male percent
sums = male_percent[['F', 'M']].sum(axis=1)
male_percent['MalePercent'] = round(100 * male_percent['M'] / sums , 1)

male_percent['MalePercent'].sort_values(ascending = False)

occupation
doctor           100.0
engineer          97.0
technician        96.3
retired           92.9
programmer        90.9
executive         90.6
scientist         90.3
entertainment     88.9
lawyer            83.3
salesman          75.0
educator          72.6
student           69.4
other             65.7
marketing         61.5
writer            57.8
none              55.6
administrator     54.4
artist            53.6
librarian         43.1
healthcare        31.2
homemaker         14.3
Name: MalePercent, dtype: float64

### Step 8. Calculate the lowest, maximum, average, and median ages for each profession.

In [13]:
df_occupation.groupby('occupation').age.agg(['min', 'max', 'mean','median'])

               min  max       mean  median
occupation
administrator   21   70  38.746835    37.0
artist          19   48  31.392857    30.0
doctor          28   64  43.571429    45.0
educator        23   63  42.010526    42.0
engineer        22   70  36.388060    36.0
entertainment   15   50  29.222222    25.0
executive       22   69  38.718750    38.5
healthcare      22   62  41.562500    44.5
homemaker       20   50  32.571429    32.0
lawyer          21   53  36.750000    34.0
librarian       23   69  40.000000    39.0
marketing       24   55  37.615385    36.0
none            11   55  26.555556    26.0
other           13   64  34.523810    32.0
programmer      20   63  33.121212    30.0
retired         51   73  63.071429    63.0
salesman        18   66  35.666667    34.0
scientist       23   55  35.548387    37.0
student          7   42  22.081633    21.0
technician      21   55  33.148148    30.0
writer          18   60  36.311111    36.0

### Step 9. Show the mean age of every combination of 'age' and 'gender'

#### Option A

In [14]:
occupation_age_gender = df_occupation.groupby(by=["occupation","gender"]).age.mean()
occupation_age_gender.astype(int)

occupation     gender
administrator  F         40
               M         37
artist         F         30
               M         32
doctor         M         43
educator       F         39
               M         43
engineer       F         29
               M         36
entertainment  F         31
               M         29
executive      F         44
               M         38
healthcare     F         39
               M         45
homemaker      F         34
               M         23
lawyer         F         39
               M         36
librarian      F         40
               M         40
marketing      F         37
               M         37
none           F         36
               M         18
other          F         35
               M         34
programmer     F         32
               M         33
retired        F         70
               M         62
salesman       F         27
               M         38
scientist      F         28
               M         36
student        F         20
               M         22
technician     F         38
               M         32
writer         F         37
               M         35
Name: age, dtype: int64

#### Option B

In [15]:
occupation_age_gender = df_occupation.groupby(by=["occupation","gender"])[["age"]].mean()
occupation_age_gender.astype(int).add_prefix("MeanOf_").reset_index()

       occupation gender  MeanOf_age
0   administrator      F          40
1   administrator      M          37
2          artist      F          30
3          artist      M          32
4          doctor      M          43
5        educator      F          39
6        educator      M          43
7        engineer      F          29
8        engineer      M          36
9   entertainment      F          31
10  entertainment      M          29
11      executive      F          44
12      executive      M          38
13     healthcare      F          39
14     healthcare      M          45
15      homemaker      F          34
16      homemaker      M          23
17         lawyer      F          39
18         lawyer      M          36
19      librarian      F          40
20      librarian      M          40
21      marketing      F          37
22      marketing      M          37
23           none      F          36
24           none      M          18
25          other      F          35
26          other      M          34
27     programmer      F          32
28     programmer      M          33
29        retired      F          70
30        retired      M          62
31       salesman      F          27
32       salesman      M          38
33      scientist      F          28
34      scientist      M          36
35        student      F          20
36        student      M          22
37     technician      F          38
38     technician      M          32
39         writer      F          37
40         writer      M          35

#### Option C - Reorganize

In [16]:
occup_age_gender = df_occupation.groupby(by=["occupation","gender"])[["age"]].mean().add_prefix("MeanOf_").reset_index()
occup_comb = occup_age_gender.pivot(index="occupation",columns="gender",values="MeanOf_age")
occup_comb

gender                 F          M
occupation
administrator  40.638889  37.162791
artist         30.307692  32.333333
doctor               NaN  43.571429
educator       39.115385  43.101449
engineer       29.500000  36.600000
entertainment  31.000000  29.000000
executive      44.000000  38.172414
healthcare     39.818182  45.400000
homemaker      34.166667  23.000000
lawyer         39.500000  36.200000
librarian      40.000000  40.000000
marketing      37.200000  37.875000
none           36.500000  18.600000
other          35.472222  34.028986
programmer     32.166667  33.216667
retired        70.000000  62.538462
salesman       27.000000  38.555556
scientist      28.333333  36.321429
student        20.750000  22.669118
technician     38.000000  32.961538
writer         37.631579  35.346154

### Step 10. show the percentage of males and the percentage of women in each profession.

#### Option A - see step 7 option A

####Option B

In [17]:
# Creating a new DataFrame for each gender according to count value
gender_ocup = df_occupation.groupby(['occupation', 'gender']).agg({'gender': 'count'})

# Creating a new DataFrame for each occupation according to count value
occup_count = df_occupation.groupby(['occupation']).agg('count')

# We will divide the gender_ocup with the occup_count and then multiply the result per 100
occup_gender = gender_ocup.div(occup_count, level = "occupation") * 100

round(occup_gender.loc[: , 'gender'],1)

occupation     gender
administrator  F          45.6
               M          54.4
artist         F          46.4
               M          53.6
doctor         M         100.0
educator       F          27.4
               M          72.6
engineer       F           3.0
               M          97.0
entertainment  F          11.1
               M          88.9
executive      F           9.4
               M          90.6
healthcare     F          68.8
               M          31.2
homemaker      F          85.7
               M          14.3
lawyer         F          16.7
               M          83.3
librarian      F          56.9
               M          43.1
marketing      F          38.5
               M          61.5
none           F          44.4
               M          55.6
other          F          34.3
               M          65.7
programmer     F           9.1
               M          90.9
retired        F           7.1
               M          92.9
salesman       F          25.0
               M          75.0
scientist      F           9.7
               M          90.3
student        F          30.6
               M          69.4
technician     F           3.7
               M          96.3
writer         F          42.2
               M          57.8
Name: gender, dtype: float64